version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "5179:5179"
    depends_on:
      - mssql
      - jaeger
    environment: # Add environment variables here
      ConnectionStrings__DefaultConnection: "Server=d-mssql,9000;Database=tests;User Id=sa;Password=Test@123;TrustServerCertificate=True;"

  mssql:
    image: cagrin/azure-sql-edge-arm64:latest
  
    container_name: d-mssql
    environment:
      SA_PASSWORD: "Test@123"
      ACCEPT_EULA: "Y"
    ports:
      - "9001:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  jaeger:
    image: jaegertracing/all-in-one:1.45
    container_name: d-jaeger
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "6831:6831/udp" # Jaeger Agent
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # Collector
      - "14250:14250"   # gRPC
      - "9411:9411"     # Zipkin

volumes:
  mssql-data:
