version: '3.8'

#networks:
#  my_custom_network: # Define a custom network
#    driver: bridge   # Default network driver

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "5179:5179"
    depends_on:
      - mssql
      - jaeger
    environment: # Add environment variables here
      ConnectionStrings__DefaultConnection: "Server=d-mssql,1433;Database=master;User Id=sa;Password=Test@123;TrustServerCertificate=True;"
      ASPNETCORE_HTTP_PORTS: 5179
      Jaeger__AgentHost: d-jaeger
      Jaeger__AgentPort: 6831
      
    #networks:
    #  - my_custom_network # Attach to the custom network
  mssql:
    image: cagrin/azure-sql-edge-arm64:latest
  
    container_name: d-mssql
    environment:
      SA_PASSWORD: "Test@123"
      ACCEPT_EULA: "Y"
    expose:
      - "1433"
      - "1431"
    volumes:
      - mssql-data:/var/opt/mssql
    #networks:
    #  - my_custom_network # Attach to the custom network

  jaeger:
    image: jaegertracing/all-in-one:1.45
    container_name: d-jaeger
    expose: 
    - "6831/udp"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "6831:6831/udp" # Jaeger Agent
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # Collector
      - "14250:14250"   # gRPC
      - "9411:9411"     # Zipkin
    #networks:
    #  - my_custom_network # Attach to the custom network

volumes:
  mssql-data:
